### PR TITLE
Fix incorrect overwrite of `yarn check` & fix type errors

### LINKED ISSUE #528: Type check in CI doesn't work
In CI we run `yarn check` to run the type checker script, but as `yarn check` [is a yarn command](https://classic.yarnpkg.com/lang/en/docs/cli/check/), our type checker script does not run.

We should run `yarn run check` instead, but it turns out we have some type errors, so they will have to be fixed first.

### PR DESCRIPTION
**Pull request by LudvigHz**
Fixes #528 :grimacing:

### CODE REVIEW

File: src/components/ImageBlock.tsx [hunk 1]
```diff
@@ -17,14 +17,16 @@ const ImageBlock = (props: Props): JSX.Element => {
...
     <div {...attributes}>
-      <div contentEditable={false}>
-        <img
-          src={src}
-          alt="Failed to load image..."
-          className={cx(baseClass, uploading && '_legoEditor_imgUploading')}
-        />
-      </div>
-      {children}
+      <>
```
Comment (SmithPeder) [inline src/components/ImageBlock.tsx:20]: Why? This component was only returning one div, what good does fragments here? Or am I blind?

Comment (LudvigHz) [reply src/components/ImageBlock.tsx:20]: There was a type error (likely after the react update) that the children prop in a div could only be an array of components or a component. This has always worked but I guess the new typing simplifies stuff a bit 🤷

Comment (SmithPeder) [reply src/components/ImageBlock.tsx:20]: > children prop in a div could only be an array of components or a component

hmm, ait 🤷🏻 I would think that with `children` being 0, 1 or N components the previous syntax should be legal. Since there is already a div around the whole thing. Which gives:
```jsx
// In the case of no children
<div>
  <div content></div content>
</div>

// In the case of 1 child
<div>
  <div content></div content>
  <h1> </h1>
</div>

// In the case of N children
<div>
  <div content></div content>
  <h1> </h1>
  <h1> </h1>
</div>
```

But no matter, I'll allow it

**Review by SmithPeder — DISMISSED** [review]
LGTM

File: src/components/ImageBlock.tsx (hunk 1 above)
Comment (LudvigHz) [reply src/components/ImageBlock.tsx:20]: I think in the previous case `children` on the div would be `[div, [children]]`. And fore some reason that's okay in fragments but not other stuff 🤷

Comment (eikhr) [reply src/components/ImageBlock.tsx:20]: The `children` prop here is typed as `unknown`, would it work without the fragment if it was `ReactNode`?

Comment (LudvigHz) [reply src/components/ImageBlock.tsx:20]: aaah, yeah that's the reason lol. Thanks :1st_place_medal:

**Review by eikhr — APPROVED** [review]
LGTM

File: src/components/ImageBlock.tsx (hunk 1 above)
Comment (SmithPeder) [reply src/components/ImageBlock.tsx]: Nice!!! ty @eikhr

File: .drone.yml [hunk 2]
```diff
@@ -18,7 +18,7 @@ steps:
     commands:
       - yarn lint
 
-  - name: Type check
```
Comment (ivarnakken) [inline .drone.yml:21]: lol

Comment (SmithPeder) [reply .drone.yml:21]: You're still pissed about this?

Comment (ivarnakken) [reply .drone.yml:21]: No, not now. At least @eikhr is a cultured man

Comment (SmithPeder) [reply .drone.yml:21]: Sorry, I read the situation wrong,
image
From my pov you still complained about the "Type check", but I notice that you referred to the fix

I rest my case

Mic drop
